run:
	echo "python3.6 src/launch.py">launch
	chmod 777 launch
	echo "python3.6 src/weakness.py">weakness
	chmod 777 weakness
	echo "python3.6 src/escape.py">escape
	chmod 777 escape
	echo "python3.6 src/avltree.py">avltree
	chmod 777 avltree