run:
	echo "python3.6 src/akce.py">akce
	chmod 777 akce
	echo "python3.6 src/sky_links.py">sky_links
	chmod 777 sky_links
	echo "python3.6 src/company.py">company
	chmod 777 company
	echo "python3.6 src/holidays.py">holidays
	chmod 777 holidays
	echo "python3.6 src/wander.py">wander
	chmod 777 wander
	echo "python3.6 src/communication.py">communication
	chmod 777 communication
	echo "python3.6 src/distribution.py">distribution
	chmod 777 distribution
	echo "python3.6 src/travel.py">travel
	chmod 777 travel